### ISSUE TITLE
无法启动系统

### ISSUE THREAD

**Issue by trlsmax** [peapon/dell-xps-9360#3]
您好，
我用黑果小兵的镜像 macOS High Sierra 10.13.3(17D47)正式版 with Clover 4391原版镜像 安装了系统也可以正常进入系统了。因为我的电脑的配置跟您是一样的（除了网卡还没有换），所以替换了EFI分区的CLOVER目录为您这里的CLOVER目录，想试试您的配置，结果只显示一个苹果的图标，就没有任何反应了。

**Comment by peapon** [comment]
可以使用 -v命令来看看卡在哪里的

**Comment by trlsmax** [comment]
谢谢回复
不过我现在已经不用黑苹果了，太折腾了
还是觉得原来用的Linux顺手
